debug: 1 # Range 0-4 (0 means no debug statements will print)

device: /dev/rtk2b
frame_id: gps
config_on_startup: false
uart1:
  baudrate: 115200 #460800
rate: 8
nav_rate: 8
publish:
  all: true
raw_data_stream:
  publish: false
  # dir: /home/fluxauto/ua/rtk_ws/GNSSLogs
