frequency: 10
delay: 0.2
magnetic_declination_radians: 0
zero_altitude: true
# wait_for_datum: true
broadcast_utm_transform: true
#broadcast_cartesian_transform: true
broadcast_utm_transform_as_parent_frame: true
#broadcast_cartesian_transform_as_parent_frame : true
publish_filtered_gps: true
yaw_offset: 0

